# Generated by Django 5.0.2 on 2024-03-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
